# Student grades prediction

here all the library.

In [204]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV


import warnings
warnings.filterwarnings("ignore")

In [26]:
data= pd.read_csv("Grades.csv")
data

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

# cheking first five rows of the dataset-

In [27]:
data.head()

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448

# cheking first five rows of the dataset-

In [28]:
data.tail()

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [137]:
# Drop irrelevant columns like Seat No
df = df.drop(columns=["Seat No."])

In [155]:
# Identify columns containing string values (assuming all columns except CGPA are grades)
grade_cols = df.columns.drop("CGPA")

In [156]:
# Encode categorical variables
label_encoder = LabelEncoder()
for col in grade_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [157]:
# Split the data into features (grades) and target variable (CGPA)
X = df.drop(columns=["CGPA"])
y = df["CGPA"]

# Exploratory Data Analysis (EDA)

# Checking columns

In [158]:
data.columns

Index(['Seat No.', 'PH-121', 'HS-101', 'CY-105', 'HS-105/12', 'MT-111',
       'CS-105', 'CS-106', 'EL-102', 'EE-119', 'ME-107', 'CS-107', 'HS-205/20',
       'MT-222', 'EE-222', 'MT-224', 'CS-210', 'CS-211', 'CS-203', 'CS-214',
       'EE-217', 'CS-212', 'CS-215', 'MT-331', 'EF-303', 'HS-304', 'CS-301',
       'CS-302', 'TC-383', 'MT-442', 'EL-332', 'CS-318', 'CS-306', 'CS-312',
       'CS-317', 'CS-403', 'CS-421', 'CS-406', 'CS-414', 'CS-419', 'CS-423',
       'CS-412', 'CGPA'],
      dtype='object')

In [159]:
data.shape

(571, 43)

In [160]:
df= data.drop_duplicates()
print("Rows & Columns after dropping duplicate : ", df.shape)

Rows & Columns after dropping duplicate :  (571, 43)

Not any duplicates values present in this datasets.

In [161]:
df["PH-121"].value_counts()

A-    112
A     111
B+     61
B      57
B-     56
D      44
C      33
C+     31
D+     22
A+     22
C-     19
WU      2
F       1
Name: PH-121, dtype: int64

In [162]:
df["HS-101"].value_counts()

A-    82
B-    78
C     68
B     63
B+    59
C-    50
C+    47
D     45
A     38
D+    36
A+     4
F      1
Name: HS-101, dtype: int64

# information of dataset-

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 571 entries, 0 to 570
Data columns (total 43 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Seat No.   571 non-null    object
 1   PH-121     571 non-null    object
 2   HS-101     571 non-null    object
 3   CY-105     570 non-null    object
 4   HS-105/12  570 non-null    object
 5   MT-111     569 non-null    object
 6   CS-105     571 non-null    object
 7   CS-106     569 non-null    object
 8   EL-102     569 non-null    object
 9   EE-119     569 non-null    object
 10  ME-107     569 non-null    object
 11  CS-107     569 non-null    object
 12  HS-205/20  566 non-null    object
 13  MT-222     566 non-null    object
 14  EE-222     564 non-null    object
 15  MT-224     564 non-null    object
 16  CS-210     564 non-null    object
 17  CS-211     566 non-null    object
 18  CS-203     566 non-null    object
 19  CS-214     565 non-null    object
 20  EE-217     565 non-null    object
 21  CS-212     565 non-null    object
 22  CS-215     565 non-null    object
 23  MT-331     562 non-null    object
 24  EF-303     561 non-null    object
 25  HS-304     561 non-null    object
 26  CS-301     561 non-null    object
 27  CS-302     561 non-null    object
 28  TC-383     561 non-null    object
 29  MT-442     561 non-null    object
 30  EL-332     562 non-null    object
 31  CS-318     562 non-null    object
 32  CS-306     562 non-null    object
 33  CS-312     561 non-null    object
 34  CS-317     559 non-null    object
 35  CS-403     559 non-null    object
 36  CS-421     559 non-null    object
 37  CS-406     486 non-null    object
 38  CS-414     558 non-null    object
 39  CS-419     558 non-null    object
 40  CS-423     557 non-null    object
 41  CS-412     492 non-null    object
 42  CGPA       571 non-null    float64
dtypes: float64(1), object(42)
memory usage: 196.3+ KB

using this information we can 1 column is float data types and 42 columns are object data types.

In [164]:
df.isnull().sum()

Seat No.      0
PH-121        0
HS-101        0
CY-105        1
HS-105/12     1
MT-111        2
CS-105        0
CS-106        2
EL-102        2
EE-119        2
ME-107        2
CS-107        2
HS-205/20     5
MT-222        5
EE-222        7
MT-224        7
CS-210        7
CS-211        5
CS-203        5
CS-214        6
EE-217        6
CS-212        6
CS-215        6
MT-331        9
EF-303       10
HS-304       10
CS-301       10
CS-302       10
TC-383       10
MT-442       10
EL-332        9
CS-318        9
CS-306        9
CS-312       10
CS-317       12
CS-403       12
CS-421       12
CS-406       85
CS-414       13
CS-419       13
CS-423       14
CS-412       79
CGPA          0
dtype: int64

we have some null values present in the dataset.

In [165]:
df.describe()

             CGPA
count  571.000000
mean     2.954888
std      0.620552
min      0.800000
25%      2.538000
50%      3.029000
75%      3.451000
max      3.985000

Using the describe method to cheque the float data details there are only one columns which have floating value in them and it looks like the count means standard derivation, minimum values 25% quartile, 50% quartile, 75% quartile and maximum value are all the property distributed in term of data points showing on the abnormality as such.

In [166]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Seat No.,571,571,CS-97001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PH-121,571,13,A-,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HS-101,571,12,A-,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CY-105,570,13,A,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HS-105/12,570,13,A,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-111,569,13,A-,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-105,571,11,A,151,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-106,569,13,A-,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EL-102,569,13,A-,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EE-119,569,12,A-,137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ME-107,569,13,A-,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-107,569,14,A,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HS-205/20,566,13,A-,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-222,566,14,A-,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EE-222,564,13,A,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-224,564,14,A-,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-210,564,14,A-,133,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-211,566,14,A-,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-203,566,13,A-,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-214,565,13,C,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EE-217,565,13,A-,137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-212,565,12,A-,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-215,565,14,A-,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-331,562,12,A,118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EF-303,561,12,B,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HS-304,561,14,A-,128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-301,561,12,A-,108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-302,561,11,A-,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TC-383,561,12,A,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-442,561,12,A-,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EL-332,562,13,A-,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-318,562,14,A-,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-306,562,13,A-,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-312,561,14,A+,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-317,559,12,B-,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-403,559,11,A,133,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-421,559,13,B,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-406,486,14,A-,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-414,558,13,A,176,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-419,558,12,A-,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-423,557,12,A-,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-412,492,13,A-,157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CGPA,571.0,NaN,NaN,NaN,2.954888,0.620552,0.8,2.538,3.029,3.451,3.985

In [167]:
df.nunique().to_frame("Unique Values")

           Unique Values
Seat No.             571
PH-121                13
HS-101                12
CY-105                13
HS-105/12             13
MT-111                13
CS-105                11
CS-106                13
EL-102                13
EE-119                12
ME-107                13
CS-107                14
HS-205/20             13
MT-222                14
EE-222                13
MT-224                14
CS-210                14
CS-211                14
CS-203                13
CS-214                13
EE-217                13
CS-212                12
CS-215                14
MT-331                12
EF-303                12
HS-304                14
CS-301                12
CS-302                11
TC-383                12
MT-442                12
EL-332                13
CS-318                14
CS-306                13
CS-312                14
CS-317                12
CS-403                11
CS-421                13
CS-406                14
CS-414                13
CS-419                12
CS-423                12
CS-412                13
CGPA                 491

With the uses of any nunique method we can see the total number of unique values present in all the columns.

# splitting the dataset into two variables namely X and Y for feature and lable:

In [168]:
x=df.drop("CGPA", axis=1)
y=df["CGPA"]

In [169]:
x

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C,C-,C-,C-,C-,A-,A,C-,B,A-
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D,D+,D,C,D,A-,B-,C,C,B
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,A-,B,B,A,C,A,A,A,A-,A
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,C-,D+,C,D+,C-,B-,B,C+,C+,C+
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,A-,B-,B+,B+,B-,A-,A,A-,A-,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,B+,A-,A-,A,A,A,B+,B+,B,A
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,A-,B+,B+,A,A,A-,B,A-,C,A-
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,B+,A-,B,A,B+,A,C,B+,A-,A-
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,B+,D,B,B,C-,D,C,B,B-,C
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,D+,C+,C,B-,D,F,C-,B+,D,C-

In [170]:
y

0      2.205
1      2.008
2      3.608
3      1.906
4      3.448
       ...
566    3.798
567    3.772
568    3.470
569    2.193
570    1.753
Name: CGPA, Length: 571, dtype: float64

# Resolving the class imbalance issue in our label column:

In [171]:
y.value_counts()

3.019    5
3.058    3
2.793    3
3.443    3
2.206    3
        ..
2.555    1
2.042    1
2.634    1
2.053    1
1.753    1
Name: CGPA, Length: 491, dtype: int64

# Scaling the Feature

In [172]:
y_reshaped = y.values.reshape(-1, 1)
y_scaled = scaler.fit_transform(y_reshaped)

In [173]:
y_scaled

array([[-1.20947980e+00],
       [-1.52721731e+00],
       [ 1.05339192e+00],
       [-1.69173115e+00],
       [ 7.95330996e-01],
       [ 1.14695313e-01],
       [ 3.40653976e-03],
       [ 1.42114286e-01],
       [ 6.50171727e-01],
       [ 4.71141962e-01],
       [-4.41748552e-01],
       [ 5.25979908e-01],
       [-2.62718787e-01],
       [ 9.16297054e-01],
       [ 7.87266592e-01],
       [-2.86911998e-01],
       [ 4.72754843e-01],
       [-1.88366396e+00],
       [ 9.95328211e-01],
       [ 8.51781823e-01],
       [-1.14335169e+00],
       [ 1.79365900e-03],
       [-3.04498330e-03],
       [ 1.01790854e+00],
       [ 8.38878777e-01],
       [-1.17238354e+00],
       [ 7.82427950e-01],
       [-1.23689877e+00],
       [ 3.87272162e-01],
       [-1.06593341e+00],
       [ 7.87266592e-01],
       [ 2.87273555e-01],
       [ 4.27594181e-01],
       [ 2.53403059e-01],
       [ 3.30821335e-01],
       [ 1.03405147e-01],
       [ 3.37272858e-01],
       [ 6.08236827e-01],
       [-1.27399503e+00],
       [ 1.20177695e+00],
       [ 1.25985478e-01],
       [-4.17555340e-01],
       [-1.67558822e-01],
       [ 1.66307497e-01],
       [-2.35785090e+00],
       [-1.42883158e+00],
       [-1.54657188e+00],
       [ 1.51951446e+00],
       [ 1.44048330e+00],
       [ 7.24364242e-01],
       [-1.13044864e+00],
       [-4.83683452e-01],
       [ 2.43725774e-01],
       [-2.61105906e-01],
       [ 1.09856670e-01],
       [ 8.88892204e-02],
       [ 7.17912719e-01],
       [-1.70302131e+00],
       [ 3.43724382e-01],
       [-6.20778317e-01],
       [-8.65936194e-01],
       [-6.30455602e-01],
       [-7.85292155e-01],
       [ 1.31306572e+00],
       [ 7.11475320e-02],
       [-3.01427925e-01],
       [-2.14332364e-01],
       [ 3.77594878e-01],
       [-3.86910606e-01],
       [ 1.00500550e+00],
       [ 8.63071988e-01],
       [-2.41751337e-01],
       [ 8.11459804e-01],
       [-9.91740893e-01],
       [ 4.79206366e-01],
       [-4.38522790e-01],
       [ 6.82429343e-01],
       [ 5.48560239e-01],
       [ 3.84046401e-01],
       [ 1.11629427e+00],
       [-2.25622529e-01],
       [-1.26431774e+00],
       [ 1.30016268e+00],
       [-3.09492329e-01],
       [-2.72381948e-02],
       [-1.44334751e+00],
       [-2.73203924e+00],
       [-9.30451424e-01],
       [-1.51430014e-01],
       [-9.54644636e-01],
       [-1.40463837e+00],
       [-2.54010643e+00],
       [-1.71753724e+00],
       [ 1.46145075e+00],
       [-1.85463210e+00],
       [ 1.56467512e+00],
       [ 1.55499784e+00],
       [ 4.88883651e-01],
       [ 1.62596459e+00],
       [-9.01419570e-01],
       [ 1.31790436e+00],
       [-1.91430869e+00],
       [ 3.56627428e-01],
       [ 6.13075470e-01],
       [ 1.29532403e+00],
       [ 4.08239612e-01],
       [-1.79011687e+00],
       [ 1.59854562e+00],
       [ 3.87272162e-01],
       [-1.05625612e+00],
       [ 1.29693691e+00],
       [ 9.05006888e-01],
       [-1.39979973e+00],
       [ 2.93725078e-01],
       [-1.52237867e+00],
       [-6.27229840e-01],
       [ 7.11475320e-02],
       [-1.55141052e+00],
       [ 6.11462589e-01],
       [-1.44979903e+00],
       [-6.49810171e-01],
       [-1.49495969e+00],
       [ 3.77594878e-01],
       [-6.04649509e-01],
       [ 1.12274579e+00],
       [-4.33670025e-02],
       [-4.77231929e-01],
       [ 3.53401666e-01],
       [ 1.21146836e-01],
       [-1.20464115e+00],
       [-4.14329579e-01],
       [-2.12719483e-01],
       [-8.83677882e-01],
       [-9.28838543e-01],
       [-6.06262390e-01],
       [-3.93362129e-01],
       [-2.00140425e+00],
       [-4.86909213e-01],
       [-1.94495343e+00],
       [-2.01108154e+00],
       [ 6.58236131e-01],
       [-1.92237310e+00],
       [-1.91737910e-02],
       [-3.15300112e+00],
       [ 1.53403039e+00],
       [ 1.48080532e+00],
       [ 4.22755539e-01],
       [-5.67553252e-01],
       [ 1.08081089e+00],
       [ 6.63074773e-01],
       [ 9.00168246e-01],
       [-5.22392590e-01],
       [ 6.61461893e-01],
       [-3.04639563e-02],
       [-5.67553252e-01],
       [ 4.82432127e-01],
       [ 1.14048748e+00],
       [ 3.66304712e-01],
       [ 2.56628820e-01],
       [ 1.24209897e+00],
       [ 4.93722293e-01],
       [ 8.79200796e-01],
       [ 9.93715331e-01],
       [ 4.38884347e-01],
       [-5.94958101e-02],
       [ 1.08081089e+00],
       [ 1.15661629e+00],
       [ 4.61464678e-01],
       [ 4.37285589e-02],
       [ 4.69529081e-01],
       [ 1.29693691e+00],
       [-9.75612086e-01],
       [-1.27222679e-02],
       [-9.04645332e-01],
       [ 1.23887321e+00],
       [ 5.01786697e-01],
       [-6.88519309e-01],
       [ 6.67913416e-01],
       [ 1.43727166e-01],
       [ 1.95339351e-01],
       [-3.32072660e-01],
       [ 1.92113589e-01],
       [ 1.25984066e+00],
       [-1.03851444e+00],
       [ 2.59868705e-02],
       [ 1.01629566e+00],
       [-1.45463767e+00],
       [-9.65920678e-02],
       [-5.17553948e-01],
       [-9.72386324e-01],
       [-1.47237936e+00],
       [-6.44971528e-01],
       [ 1.49532125e+00],
       [ 1.43403178e+00],
       [-1.13206152e+00],
       [ 1.20984135e+00],
       [ 8.00169639e-01],
       [ 7.58234739e-01],
       [-1.55302340e+00],
       [-4.94973617e-01],
       [-5.59488848e-01],
       [ 1.03405147e-01],
       [ 1.07758513e+00],
       [ 6.74364939e-01],
       [ 3.37272858e-01],
       [-9.80450728e-01],
       [ 2.24371205e-01],
       [ 1.03565023e+00],
       [ 1.37758095e+00],
       [-1.57881537e-01],
       [-1.99333985e+00],
       [ 1.11306851e+00],
       [-3.83684844e-01],
       [ 6.29204277e-01],
       [-1.33205874e+00],
       [ 1.93726470e-01],
       [-3.85283602e-02],
       [-1.68689250e+00],
       [-2.07866717e-02],
       [ 5.96946662e-01],
       [ 1.09856670e-01],
       [-1.19818963e+00],
       [-5.38521398e-01],
       [-3.14330971e-01],
       [ 4.42110108e-01],
       [ 5.06625339e-01],
       [ 1.14371324e+00],
       [-3.20782494e-01],
       [-9.65920678e-02],
       [-5.01425140e-01],
       [-7.94969440e-01],
       [-4.09490937e-01],
       [ 1.24532473e+00],
       [ 1.40501405e-01],
       [ 1.28887251e+00],
       [ 1.31306572e+00],
       [-1.11093871e-02],
       [-1.20786692e+00],
       [ 6.42107323e-01],
       [ 9.96941092e-01],
       [ 5.03399577e-01],
       [-3.20782494e-01],
       [-5.80456298e-01],
       [ 1.02919871e+00],
       [ 5.09851101e-01],
       [-5.64327490e-01],
       [ 1.66307497e-01],
       [-4.32071267e-01],
       [ 7.69524904e-01],
       [-2.74008952e-01],
       [ 6.01785304e-01],
       [-3.20782494e-01],
       [ 1.42114286e-01],
       [-8.30452817e-01],
       [ 8.98555365e-01],
       [-1.92076021e+00],
       [-5.64327490e-01],
       [-1.03851444e+00],
       [ 8.45330300e-01],
       [ 7.93718115e-01],
       [ 1.28403387e+00],
       [-7.59486063e-01],
       [-4.04652294e-01],
       [-2.40138456e-01],
       [ 1.29048539e+00],
       [-4.82056448e-02],
       [ 9.43716027e-01],
       [-9.14322617e-01],
       [ 8.35653015e-01],
       [-1.77236106e-01],
       [ 9.67909238e-01],
       [-1.62720179e-01],
       [ 1.61468855e-01],
       [-9.09483974e-01],
       [-5.41747159e-01],
       [-1.69334403e+00],
       [-1.52560443e+00],
       [-4.03039413e-01],
       [-8.82065001e-01],
       [-1.05948189e+00],
       [ 9.13071292e-01],
       [-3.00461609e+00],
       [-1.40141261e+00],
       [-1.40141261e+00],
       [ 1.55499784e+00],
       [ 1.64048052e+00],
       [ 1.45338635e+00],
       [ 1.31790436e+00],
       [-3.15622688e+00],
       [ 1.59370698e+00],
       [ 1.87274947e-01],
       [ 1.04855328e+00],
       [ 1.12597155e+00],
       [-1.74011757e+00],
       [ 1.15016476e+00],
       [-2.64331668e-01],
       [-1.67076370e+00],
       [-2.90137760e-01],
       [-4.85296333e-01],
       [ 7.43718812e-01],
       [ 1.00179386e-01],
       [ 1.13081020e+00],
       [ 1.35983926e+00],
       [-3.53040110e-01],
       [ 3.24369812e-01],
       [ 1.42758026e+00],
       [ 1.66307497e-01],
       [ 5.85656497e-01],
       [-5.30442871e-02],
       [-1.22399572e+00],
       [ 6.13075470e-01],
       [ 1.13564884e+00],
       [ 3.42111501e-01],
       [ 7.46944573e-01],
       [-3.64330275e-01],
       [ 1.26145354e+00],
       [ 1.69533259e-01],
       [ 1.25985478e-01],
       [ 8.40491658e-01],
       [-1.23206013e+00],
       [-1.11109407e+00],
       [ 6.05011066e-01],
       [-1.72398876e+00],
       [-6.59473332e-02],
       [-1.49495969e+00],
       [ 9.98553973e-01],
       [-1.61269999e+00],
       [-1.53528171e+00],
       [ 4.90496531e-01],
       [ 1.10661698e+00],
       [-5.74004775e-01],
       [-1.23689877e+00],
       [-3.85297725e-01],
       [-5.41747159e-01],
       [ 6.46960089e-02],
       [-1.64334472e+00],
       [ 1.06468208e+00],
       [-7.53034540e-01],
       [ 7.30815766e-01],
       [-7.49808778e-01],
       [-1.85624498e+00],
       [-1.20785279e-01],
       [ 3.69530474e-01],
       [ 4.69543205e-02],
       [-9.20774140e-01],
       [-1.15948049e+00],
       [ 2.17919682e-01],
       [ 1.18403526e+00],
       [-1.40463837e+00],
       [ 7.11461196e-01],
       [ 1.12274579e+00],
       [ 1.22435728e+00],
       [-2.00301713e+00],
       [ 6.96945269e-01],
       [ 8.66297750e-01],
       [ 7.05009673e-01],
       [ 8.00169639e-01],
       [ 1.19209966e+00],
       [ 4.80819247e-01],
       [ 1.37274231e+00],
       [ 8.42104538e-01],
       [ 7.00171031e-01],
       [ 1.39532264e+00],
       [ 1.74371901e-01],
       [ 4.37271466e-01],
       [ 1.23564745e+00],
       [ 1.35500062e+00],
       [ 8.55007585e-01],
       [ 7.77589308e-01],
       [-7.14325401e-01],
       [ 1.06952073e+00],
       [ 1.09048818e+00],
       [ 1.21306711e+00],
       [ 3.24369812e-01],
       [ 8.64684869e-01],
       [-7.69163348e-01],
       [ 9.66296358e-01],
       [-6.41745767e-01],
       [-6.93357951e-01],
       [ 1.07435937e+00],
       [ 7.85653712e-01],
       [-2.49815741e-01],
       [-1.82076161e+00],
       [-1.67558822e-01],
       [-3.85283602e-02],
       [-2.61105906e-01],
       [-5.54650206e-01],
       [-2.09172558e+00],
       [-6.38520005e-01],
       [ 4.67916201e-01],
       [-3.30459779e-01],
       [ 1.32437001e-01],
       [ 7.09848316e-01],
       [-2.61105906e-01],
       [ 2.92112197e-01],
       [ 2.24371205e-01],
       [ 3.22756932e-01],
       [-1.33367162e+00],
       [ 4.03400970e-01],
       [-6.14326794e-01],
       [-8.12711128e-01],
       [-1.02238563e+00],
       [-9.30451424e-01],
       [-1.01109546e+00],
       [-6.56261694e-01],
       [-5.14328186e-01],
       [ 4.42110108e-01],
       [-2.83686237e-01],
       [-9.86902251e-01],
       [-1.09819102e+00],
       [-1.47560512e+00],
       [-1.48528241e+00],
       [-7.25615567e-01],
       [-1.12077135e+00],
       [ 2.38887132e-01],
       [-1.61915151e+00],
       [-2.93363521e-01],
       [ 6.11462589e-01],
       [ 8.40491658e-01],
       [ 1.30661420e+00],
       [ 6.46945966e-01],
       [ 5.40495835e-01],
       [-1.62237727e+00],
       [-1.94817919e+00],
       [-1.80624568e+00],
       [ 4.06626731e-01],
       [ 1.26790506e+00],
       [ 1.66144797e+00],
       [ 8.42104538e-01],
       [-6.11086909e-02],
       [ 7.56621858e-01],
       [-2.75621833e-01],
       [-4.12716698e-01],
       [ 8.48556062e-01],
       [ 9.53407435e-02],
       [ 9.74360761e-01],
       [ 1.25016337e+00],
       [ 1.41306433e+00],
       [ 4.25981301e-01],
       [ 1.03405147e-01],
       [ 1.29209827e+00],
       [-1.03043591e-01],
       [ 3.61466070e-01],
       [ 2.93725078e-01],
       [-8.56258909e-01],
       [-3.51427229e-01],
       [-1.55786204e+00],
       [-1.73044028e+00],
       [ 9.16297054e-01],
       [ 1.53725615e+00],
       [ 1.00823126e+00],
       [-9.72386324e-01],
       [ 6.08236827e-01],
       [-3.20768371e-02],
       [-1.66431217e+00],
       [-5.94958101e-02],
       [-5.53037325e-01],
       [-1.00141818e+00],
       [-1.20786692e+00],
       [ 1.59209409e+00],
       [ 7.25977123e-01],
       [ 1.43241890e+00],
       [ 6.19526993e-01],
       [ 1.39209688e+00],
       [ 1.05177904e+00],
       [ 9.24361458e-01],
       [ 3.13079647e-01],
       [-1.11431983e+00],
       [-1.48366953e+00],
       [ 1.22435728e+00],
       [-4.01426533e-01],
       [ 6.19526993e-01],
       [ 1.48564396e+00],
       [ 1.03405147e-01],
       [-3.09492329e-01],
       [ 2.51790178e-01],
       [ 4.13078255e-01],
       [-8.72387717e-01],
       [-2.83686237e-01],
       [ 2.32435609e-01],
       [-8.24001294e-01],
       [-1.70785995e+00],
       [-1.36914087e-01],
       [ 1.11790715e+00],
       [ 1.47274092e+00],
       [ 5.61463285e-01],
       [ 8.88892204e-02],
       [ 2.56628820e-01],
       [ 9.69536242e-02],
       [-1.72398876e+00],
       [-8.27227055e-01],
       [-1.27222679e-02],
       [-5.69166132e-01],
       [ 6.37268681e-01],
       [ 1.48886973e+00],
       [ 1.00177973e+00],
       [ 6.30817158e-01],
       [ 1.01306990e+00],
       [ 1.63725476e+00],
       [ 1.60338426e+00],
       [ 8.48556062e-01],
       [ 1.30338844e+00],
       [-2.78847594e-01],
       [ 1.46467651e+00],
       [ 1.21951864e+00],
       [ 7.87266592e-01],
       [ 2.45338655e-01],
       [ 2.59854582e-01],
       [ 1.63081736e-01],
       [-1.55302340e+00],
       [ 4.59851797e-01],
       [-7.59486063e-01],
       [-1.07561069e+00],
       [-7.51421659e-01],
       [ 1.16308193e-01],
       [-2.88524879e-01],
       [-1.61592575e+00],
       [ 5.11463981e-01],
       [-6.27074484e-03],
       [ 4.37285589e-02],
       [ 8.24518206e-03],
       [-1.76108502e+00],
       [-1.85301922e+00],
       [-1.01109546e+00],
       [-6.11101032e-01],
       [-2.23995525e-02],
       [-4.77231929e-01],
       [-1.60947423e+00],
       [ 1.25661490e+00],
       [ 1.48564396e+00],
       [ 1.59209409e+00],
       [ 9.85650927e-01],
       [ 1.82436305e-01],
       [ 1.16790645e+00],
       [ 6.67913416e-01],
       [ 6.61461893e-01],
       [ 8.85652319e-01],
       [ 6.95332389e-01],
       [ 8.77587915e-01],
       [ 8.01782519e-01],
       [ 1.30661420e+00],
       [ 1.19532543e+00],
       [ 1.38887112e+00],
       [ 1.05177904e+00],
       [ 1.19533955e-01],
       [ 1.82436305e-01],
       [ 1.03405147e-01],
       [-1.30463976e+00],
       [ 3.66304712e-01],
       [-1.53042895e-01],
       [-9.61096159e-01],
       [ 4.24368420e-01],
       [-8.85290763e-01],
       [ 8.64684869e-01],
       [-1.20785279e-01],
       [-1.20786692e+00],
       [ 1.07919801e+00],
       [-8.48194505e-01],
       [ 3.50175905e-01],
       [ 4.37271466e-01],
       [-9.43354470e-01],
       [-2.04655079e-01],
       [-2.15945245e-01],
       [-5.53037325e-01],
       [-5.61101729e-01],
       [-3.47557727e+00],
       [ 1.35983926e+00],
       [ 1.31790436e+00],
       [ 8.30814373e-01],
       [-1.22883437e+00],
       [-1.93850190e+00]])

In [174]:
df.skew()

CGPA   -0.497203
dtype: float64

# Split the data into training and testing sets

In [209]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# linear regression model

In [210]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Accuracy:", accuracy)

Accuracy: 0.790603838246097

# Decision Tree

In [198]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

print("Accuracy:", accuracy)

Accuracy: 0.790603838246097

# SVM

In [211]:
svm_regressor = SVR()
svm_regressor.fit(X_train, y_train)

print("Accuracy:", accuracy)

Accuracy: 0.790603838246097

# Conclusion

Accuracy: 0.790603838246097     all the method predict same Accuracy.